In [41]:
import pandas as pd
import numpy as np
import requests
import datetime

In [190]:
Type_List_01 = pd.Series({'CU':'沪铜',
            'NI':'沪镍',
            'J9':'焦炭',
            'PB':'沪铅',
            'JM':'焦煤',
            'I9':'铁矿',
            'JD':'鸡蛋',
            'RU':'橡胶',
            'Y9':'豆油',
            'SR':'白糖',
            'AL':'沪铝',
            'HC':'热卷',
            'RB':'螺纹',
            'ZC':'郑煤',
            'MA':'甲醇',
            'ZN':'沪锌',
            'RM':'菜粕',
            'C9':'玉米',
            'M9':'豆粕'})

Type_List_02 = pd.Series({'CU':'沪铜',
            'NI':'沪镍',
            'J':'焦炭',
            'PB':'沪铅',
            'JM':'焦煤',
            'I':'铁矿',
            'JD':'鸡蛋',
            'RU':'橡胶',
            'Y':'豆油',
            'SR':'白糖',
            'AL':'沪铝',
            'HC':'热卷',
            'RB':'螺纹',
            'ZC':'郑煤',
            'MA':'甲醇',
            'ZN':'沪锌',
            'RM':'菜粕',
            'C':'玉米',
            'M':'豆粕'})

In [191]:
Type_List_02 = pd.Series(Type_List_02.index)
Type_List_02.index = Type_List_01.index

In [192]:
Type_List_02

AL    AL
C9     C
CU    CU
HC    HC
I9     I
J9     J
JD    JD
JM    JM
M9     M
MA    MA
NI    NI
PB    PB
RB    RB
RM    RM
RU    RU
SR    SR
Y9     Y
ZC    ZC
ZN    ZN
dtype: object

In [ ]:
link_60m = 'http://stock2.finance.sina.com.cn/futures/api/json.php/IndexService.getInnerFuturesMiniKLine60m?symbol='+Type_List_02[name]+'0'
        r_01 = requests.get(link_60m)
        New_Data = pd.DataFrame(r_01.json(),columns =['Time','Open','High','Low','Close','Vol'])
        Last_time = list(DF.Time)[0]
        Last_time = datetime.datetime.strptime(Last_time,"%Y/%m/%d %H:%M")
        Last_time = Last_time.strftime('%Y-%m-%d %H:%M:%S')
        the_num = New_Data[New_Data.Time==Last_time].index[0]-1 #第一天
        New_Data = New_Data.iloc[:the_num,:]
        New_index = range(-len(New_Data),0)
        New_Data.index = New_index
        N_time = []
        for t in DF.Time:
            nt = datetime.datetime.strptime(t,"%Y/%m/%d %H:%M")
            nt = nt.strftime('%Y-%m-%d %H:%M:%S')
            N_time.append(nt)
        DF.Time = N_time
        DF.loc[:,['Open','High','Low','Close']] = DF.loc[:,['Open','High','Low','Close']].astype('float64')
        New_Data.loc[:,['Open','High','Low','Close']] = New_Data.loc[:,['Open','High','Low','Close']].astype('float64')        
        DF = pd.concat([New_Data,DF])

In [198]:
for name in Type_List_01.index:
    try:
        DF = pd.read_csv('1hour\\'+name+'1h.csv',sep=',',encoding='gb2312')
        DF = DF.iloc[:,0:6]
        DF.columns = ['Time','Open','High','Low','Close','Vol']
        link_60m = 'http://stock2.finance.sina.com.cn/futures/api/json.php/IndexService.getInnerFuturesMiniKLine60m?symbol='+Type_List_02[name]+'0'
        r_01 = requests.get(link_60m)
        New_Data = pd.DataFrame(r_01.json(),columns =['Time','Open','High','Low','Close','Vol'])
        Last_time = list(DF.Time)[0]
        Last_time = datetime.datetime.strptime(Last_time,"%Y/%m/%d %H:%M")
        Last_time = Last_time.strftime('%Y-%m-%d %H:%M:%S')
        the_num = New_Data[New_Data.Time==Last_time].index[0]-1 #第一天
        New_Data = New_Data.iloc[:the_num,:]
        New_index = range(-len(New_Data),0)
        New_Data.index = New_index
        N_time = []
        for t in DF.Time:
            nt = datetime.datetime.strptime(t,"%Y/%m/%d %H:%M")
            nt = nt.strftime('%Y-%m-%d %H:%M:%S')
            N_time.append(nt)
        DF.Time = N_time
        DF.loc[:,['Open','High','Low','Close']] = DF.loc[:,['Open','High','Low','Close']].astype('float64')
        New_Data.loc[:,['Open','High','Low','Close']] = New_Data.loc[:,['Open','High','Low','Close']].astype('float64')        
        DF = pd.concat([New_Data,DF])
        #DF = DF.sort_index(ascending = False)
        DF.to_csv('1hour\\'+name+'1h.csv',index = False)
        print(Type_List_01[name]+':'+str(list(DF.Time)[0]))
    except:
        print(name+'Wrong')

沪铝:2018-09-19 15:00:00
玉米:2018-09-19 15:00:00
沪铜:2018-09-19 15:00:00
热卷:2018-09-19 15:00:00
铁矿:2018-09-19 15:00:00
焦炭:2018-09-19 15:00:00
鸡蛋:2018-09-19 15:00:00
焦煤:2018-09-19 15:00:00
豆粕:2018-09-19 15:00:00
甲醇:2018-09-19 15:00:00
沪镍:2018-09-19 15:00:00
沪铅:2018-09-19 15:00:00
螺纹:2018-09-19 15:00:00
菜粕:2018-09-19 15:00:00
橡胶:2018-09-19 15:00:00
白糖:2018-09-19 15:00:00
豆油:2018-09-19 15:00:00
郑煤:2018-09-19 15:00:00
沪锌:2018-09-19 15:00:00

In [194]:
link_60m = 'http://stock2.finance.sina.com.cn/futures/api/json.php/IndexService.getInnerFuturesMiniKLine60m?symbol=MA0'
r_01 = requests.get(link_60m)
New_Data = pd.DataFrame(r_01.json(),columns =['Time','Open','High','Low','Close','Vol'])
New_Data

                    Time      Open      High       Low     Close     Vol
0    2018-09-19 15:00:00  3305.000  3338.000  3305.000  3338.000  318162
1    2018-09-19 14:00:00  3295.000  3299.000  3289.000  3296.000   60628
2    2018-09-19 11:30:00  3294.000  3297.000  3289.000  3295.000   37996
3    2018-09-19 11:00:00  3297.000  3302.000  3286.000  3295.000   96210
4    2018-09-19 10:00:00  3279.000  3306.000  3277.000  3293.000  173412
5    2018-09-19 00:00:00  3272.000  3282.000  3270.000  3281.000   66150
6    2018-09-18 23:00:00  3278.000  3280.000  3272.000  3277.000   93438
7    2018-09-18 22:00:00  3261.000  3283.000  3257.000  3279.000  334838
8    2018-09-18 15:00:00  3250.000  3255.000  3237.000  3250.000  185206
9    2018-09-18 14:00:00  3259.000  3273.000  3248.000  3252.000  148884
10   2018-09-18 11:30:00  3256.000  3261.000  3252.000  3256.000   31494
11   2018-09-18 11:00:00  3258.000  3265.000  3250.000  3254.000   80560
12   2018-09-18 10:00:00  3250.000  3271.000  3229.000  3260.000  257760
13   2018-09-18 00:00:00  3255.000  3257.000  3251.000  3255.000   41452
14   2018-09-17 23:00:00  3259.000  3262.000  3250.000  3252.000   78998
15   2018-09-17 22:00:00  3265.000  3269.000  3249.000  3260.000  246718
16   2018-09-17 15:00:00  3226.000  3263.000  3226.000  3263.000  226430
17   2018-09-17 14:00:00  3224.000  3228.000  3214.000  3227.000   86856
18   2018-09-17 11:30:00  3246.000  3246.000  3216.000  3220.000   98122
19   2018-09-17 11:00:00  3258.000  3259.000  3223.000  3241.000  146358
20   2018-09-17 10:00:00  3252.000  3268.000  3242.000  3260.000  152996
21   2018-09-15 00:00:00  3230.000  3274.000  3227.000  3269.000  218952
22   2018-09-14 23:00:00  3222.000  3230.000  3203.000  3229.000  256872
23   2018-09-14 22:00:00  3263.000  3265.000  3217.000  3220.000  289612
24   2018-09-14 15:00:00  3274.000  3274.000  3252.000  3259.000  120602
25   2018-09-14 14:00:00  3276.000  3276.000  3268.000  3270.000   30972
26   2018-09-14 11:30:00  3268.000  3279.000  3268.000  3276.000   71514
27   2018-09-14 11:00:00  3264.000  3270.000  3259.000  3269.000   43146
28   2018-09-14 10:00:00  3259.000  3267.000  3248.000  3267.000   95274
29   2018-09-14 00:00:00  3255.000  3257.000  3251.000  3256.000   29744
..                   ...       ...       ...       ...       ...     ...
162  2018-08-22 11:30:00  3454.000  3516.000  3454.000  3516.000  508628
163  2018-08-22 11:00:00  3382.000  3468.000  3376.000  3449.000  531998
164  2018-08-22 10:00:00  3357.000  3388.000  3357.000  3382.000  206674
165  2018-08-22 00:00:00  3336.000  3368.000  3323.000  3366.000  224066
166  2018-08-21 23:00:00  3330.000  3343.000  3329.000  3338.000   98116
167  2018-08-21 22:00:00  3334.000  3340.000  3318.000  3331.000  182336
168  2018-08-21 15:00:00  3328.000  3343.000  3321.000  3334.000  146690
169  2018-08-21 14:00:00  3348.000  3348.000  3306.000  3322.000  184850
170  2018-08-21 11:30:00  3355.000  3360.000  3339.000  3345.000   79694
171  2018-08-21 11:00:00  3359.000  3361.000  3352.000  3356.000   76326
172  2018-08-21 10:00:00  3380.000  3380.000  3336.000  3358.000  285060
173  2018-08-21 00:00:00  3373.000  3376.000  3367.000  3369.000   66520
174  2018-08-20 23:00:00  3382.000  3389.000  3368.000  3373.000  149352
175  2018-08-20 22:00:00  3360.000  3392.000  3360.000  3384.000  310984
176  2018-08-20 15:00:00  3324.000  3422.000  3322.000  3372.000  554956
177  2018-08-20 14:00:00  3264.000  3329.000  3263.000  3323.000  260628
178  2018-08-20 11:30:00  3264.000  3266.000  3250.000  3262.000   46240
179  2018-08-20 11:00:00  3279.000  3279.000  3257.000  3261.000   86938
180  2018-08-20 10:00:00  3245.000  3282.000  3236.000  3278.000  208728
181  2018-08-18 00:00:00  3230.000  3252.000  3226.000  3251.000   74740
182  2018-08-17 23:00:00  3264.000  3265.000  3216.000  3230.000  277732
183  2018-08-17 22:00:00  3277.000  3293.000  3263.000  3268.000  204026
184  2018-08-17 15:00:00  3295.000  3296.000  3254.000  3266.000  207608
185  2018-08-17 14:00:00  3276.000  3310.000  3276.000  3297.000  202966
186  2018-08-17 11:00:00  3269.000  3270.000  3261.000  3266.000   29020
187  2018-08-17 10:00:00  3282.000  3284.000  3260.000  3269.000  196848
188  2018-08-17 00:00:00  3275.000  3283.000  3269.000  3282.000   72472
189  2018-08-16 23:00:00  3286.000  3290.000  3269.000  3277.000  202254
190  2018-08-16 22:00:00  3337.000  3350.000  3272.000  3284.000  455608
191  2018-08-16 15:00:00  3321.000  3335.000  3304.000  3329.000  223408

[192 rows x 6 columns]

In [199]:
for name in Type_List_01.index:
    try:
        DF = pd.read_csv('30min\\'+name+'30m.csv',sep=',',encoding='gb2312')
        DF = DF.iloc[:,0:6]
        DF.columns = ['Time','Open','High','Low','Close','Vol'] 
        link_30m = 'http://stock2.finance.sina.com.cn/futures/api/json.php/IndexService.getInnerFuturesMiniKLine30m?symbol='+Type_List_02[name]+'0'
        r_01 = requests.get(link_30m)
        New_Data = pd.DataFrame(r_01.json(),columns =['Time','Open','High','Low','Close','Vol'])
        Last_time = list(DF.Time)[0]
        Last_time = datetime.datetime.strptime(Last_time,"%Y/%m/%d %H:%M")
        Last_time = Last_time.strftime('%Y-%m-%d %H:%M:%S')
        the_num = New_Data[New_Data.Time==Last_time].index[0]-1 #第一天
        New_Data = New_Data.iloc[:the_num,:]
        New_index = range(-len(New_Data),0)
        New_Data.index = New_index
        N_time = []
        for t in DF.Time:
            nt = datetime.datetime.strptime(t,"%Y/%m/%d %H:%M")
            nt = nt.strftime('%Y-%m-%d %H:%M:%S')
            N_time.append(nt)
        DF.Time = N_time
        DF.loc[:,['Open','High','Low','Close']] = DF.loc[:,['Open','High','Low','Close']].astype('float64')
        New_Data.loc[:,['Open','High','Low','Close']] = New_Data.loc[:,['Open','High','Low','Close']].astype('float64')        
        DF = pd.concat([New_Data,DF])
        
        #DF = DF.sort_index(ascending = False)
        DF.to_csv('30min\\'+name+'30m.csv',index = False)
        print(Type_List_01[name]+':'+str(DF.Time[0]))
    except:
        print(name+'Wrong')

沪铝:2018-09-18 23:30:00
玉米:2018-09-18 14:30:00
沪铜:2018-09-18 23:30:00
热卷:2018-09-18 22:30:00
铁矿:2018-09-18 23:00:00
焦炭:2018-09-18 23:00:00
鸡蛋:2018-09-18 14:30:00
焦煤:2018-09-18 23:00:00
豆粕:2018-09-18 23:00:00
甲醇:2018-09-18 23:00:00
沪镍:2018-09-18 23:30:00
沪铅:2018-09-18 23:30:00
螺纹:2018-09-18 22:30:00
菜粕:2018-09-18 23:00:00
橡胶:2018-09-18 22:30:00
白糖:2018-09-18 23:00:00
豆油:2018-09-18 23:00:00
郑煤:2018-09-18 23:00:00
沪锌:2018-09-18 23:30:00

In [200]:
for name in Type_List_01.index:
    try:
        DF = pd.read_csv('15min\\'+name+'15m.csv',sep=',',encoding='gb2312')
        DF = DF.iloc[:,0:6]
        DF.columns = ['Time','Open','High','Low','Close','Vol'] 
        
        link_60m = 'http://stock2.finance.sina.com.cn/futures/api/json.php/IndexService.getInnerFuturesMiniKLine15m?symbol='+Type_List_02[name]+'0'
        r_01 = requests.get(link_60m)
        New_Data = pd.DataFrame(r_01.json(),columns =['Time','Open','High','Low','Close','Vol'])
        Last_time = list(DF.Time)[0]
        Last_time = datetime.datetime.strptime(Last_time,"%Y/%m/%d %H:%M")
        Last_time = Last_time.strftime('%Y-%m-%d %H:%M:%S')
        the_num = New_Data[New_Data.Time==Last_time].index[0]-1 #第一天
        New_Data = New_Data.iloc[:the_num,:]
        New_index = range(-len(New_Data),0)
        New_Data.index = New_index
        N_time = []
        for t in DF.Time:
            nt = datetime.datetime.strptime(t,"%Y/%m/%d %H:%M")
            nt = nt.strftime('%Y-%m-%d %H:%M:%S')
            N_time.append(nt)
        DF.Time = N_time
        DF.loc[:,['Open','High','Low','Close']] = DF.loc[:,['Open','High','Low','Close']].astype('float64')
        New_Data.loc[:,['Open','High','Low','Close']] = New_Data.loc[:,['Open','High','Low','Close']].astype('float64')        
        DF = pd.concat([New_Data,DF])
        
        #DF = DF.sort_index(ascending = False)
        DF.to_csv('15min\\'+name+'15m.csv',index = False)
        print(Type_List_01[name]+':'+str(list(DF.Time)[0]))
    except:
        print(name+'Wrong')

ALWrong
C9Wrong
CUWrong
HCWrong
I9Wrong
J9Wrong
JDWrong
JMWrong
M9Wrong
MAWrong
NIWrong
PBWrong
RBWrong
RMWrong
RUWrong
SRWrong
Y9Wrong
ZCWrong
ZNWrong

In [83]:
for name in Type_List_01.index:
    try:
        DF = pd.read_csv('5min\\'+name+'5m.csv',sep=',',encoding='gb2312')
        DF = DF.iloc[:,0:6]
        DF.columns = ['Time','Open','High','Low','Close','Vol'] 
        #DF = DF.sort_index(ascending = False)
        DF.to_csv('5min\\'+name+'5m.csv',index = False)
        print(Type_List_01[name]+':'+str(DF.Time[0]))
    except:
        print(name+'Wrong')

沪铝:2018/09/18 23:55
玉米:2018/09/18 14:55
沪铜:2018/09/18 23:55
热卷:2018/09/18 22:55
铁矿:2018/09/18 23:25
焦炭:2018/09/18 23:25
鸡蛋:2018/09/18 14:55
焦煤:2018/09/18 23:25
豆粕:2018/09/18 23:25
甲醇:2018/09/18 23:25
沪镍:2018/09/18 23:55
沪铅:2018/09/18 23:55
螺纹:2018/09/18 22:55
菜粕:2018/09/18 23:25
橡胶:2018/09/18 22:55
白糖:2018/09/18 23:25
豆油:2018/09/18 23:25
郑煤:2018/09/18 23:25
沪锌:2018/09/18 23:55